language: java
jdk:
- openjdk13
deploy:
  provider: heroku
  app: service-c
  api_key:
    secure: JjhpZ1cbIDoSqAkOBF5lm0Jn++1dzUTpYUeGzBS9jlVezbXWPEVh5LZCD9BsKH31copRZk4rIkJIag5WuCLxEjXMIlARPQcQyNnW1E5k8tdELYZhca7Dp/fIAwERUUxT7VsAOovr88nxxLfDndhjVG/SA30PAmwXtqr5ZIfZ0G2M192/EEznmeiYH5Oh9pO80UwTryqNYKRSxhNmhp5mPOnxL9bDhRe/VimO0rlvoEU1XhIPbJH1EXPmVJ2SHFfLPsWlAkEwLCJjie2xm0hLLP8wBz1xhr7q5z1KvFhGVzNIG3boubDvrVuDON3Wv+fa4NpdYdpuuRctSjCnSUJdW/YvgUIE1gpkZcscLLiLzhhFzf39IDSajTr0NiZRZEIVpGCLLvcMyY49VuYI3PDjEA1ATxORPwPi+3BxFQOLAGFEkwsDQ//qJL92k2VB2TQo2CzpWTpmx1YigUzE9qkz8sVnl+8AgJMEs8xyhql79GdwrHKnTyT8mgmHbEGA9iX5Hzs1Rz+cFAtk33NgJM4I3SK6Wpky4eXOlByLh+KjSHRmPHxTwrWHgBKIN7QhlrEQ9XBVK2U3agvAHUpcrTJomJ8TKVE0q0+TvPrYdKxmILPzXY0HPa1rvUwem/GlJ2NkJeWjCQrH/PBqLzuvnkVOWAQsoPqPX+lwzYRbHKyKNFI=
